version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: volume
        source: backend_data
        target: /app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///data/babyfoot_tournament.db
    networks:
      - babyfoot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${API_URL:-http://backend:8000/api}
      - .env
    depends_on:
      - backend
    networks:
      - babyfoot-network

networks:
  babyfoot-network:
    driver: bridge

volumes:
  backend_data:
    driver: local 